#!/usr/bin/env bash
set -eu

#######################################
# 作用: 倒计时(默认是数字)
# 参数:
#   -n: 输出数字来倒计时
#   $1: 秒数
# 输出:
#   3 2 1 0  或者  ....
#######################################
function print_usage() {
    echo 'Usage:'
    echo '    count_down -n [seconds]'
    echo "    -n print number"
    echo ''
    echo "Examples:"
    echo "    count_down 3"
}

#######################################
# flags

declare use_number='false'
declare option
while getopts nh option; do
    case $option in
        n) use_number='true' ;;
        h) print_usage; exit 0; ;;
        *) print_usage; exit 1; ;;
    esac
done
shift $((OPTIND - 1))

#######################################

utils_dir="$(cd "$(dirname "$0")"; pwd)"
declare -r utils_dir
if echo "$PATH" | grep -v "$utils_dir" &> /dev/null; then
    export PATH="$utils_dir:$PATH"
fi

declare i
if [[ $use_number == 'true' ]]; then
    for i in $(seq "$1" -1 1); do
        echo -n "$i " | color_print 102
        sleep 1
    done
    color_print 102 '0'
else
    for i in $(seq "$1" -1 1); do
        color_print 102 '.'
        sleep 1
    done
    echo ''
fi
